import { IsEnum, IsInt, IsPositive, IsOptional, IsString } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { PaymentType } from '../entities/payment.entity';

export class CreatePaymentDto {
  @ApiProperty({
    enum: PaymentType,
    description: 'Type of payment: inscription, abonnement, or versement_ponctuel',
    example: PaymentType.INSCRIPTION,
  })
  @IsEnum(PaymentType)
  paymentType: PaymentType;

  @ApiProperty({
    description: 'Amount in euro cents (e.g. 9900 = €99.00)',
    example: 9900,
  })
  @IsInt()
  @IsPositive()
  amountCents: number;

  @ApiPropertyOptional({
    description: 'External transaction reference from payment provider',
    example: 'stripe_pi_abc123',
  })
  @IsOptional()
  @IsString()
  externalReference?: string;

  @ApiPropertyOptional({ description: 'Correlation ID for inter-service tracing' })
  @IsOptional()
  @IsString()
  correlationId?: string;

  /**
   * Optional idempotency key provided by the caller.
   * If a payment with the same (ownerId, idempotencyKey) already exists, the existing
   * payment is returned without creating a new one. Use this to safely retry POST /payments
   * without risk of creating duplicate payments.
   * Example: a UUID generated by the client before the first request attempt.
   */
  @ApiPropertyOptional({
    description:
      'Idempotency key to prevent duplicate payments on retry. ' +
      'If a payment with the same (ownerId, idempotencyKey) already exists, ' +
      'the existing result is returned (HTTP 201) without re-executing the workflow.',
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  })
  @IsOptional()
  @IsString()
  idempotencyKey?: string;
}
